-- AlterTable
ALTER TABLE `products` ADD COLUMN `public_category` ENUM('ELECTRONICS', 'COMPUTERS', 'PHONES', 'CAMERAS', 'FASHION', 'JEWELRY', 'WATCHES', 'HOME', 'FURNITURE', 'BOOKS', 'ART', 'TOYS', 'FIGURES', 'COLLECTIBLES', 'ANTIQUES', 'SPORTS', 'AUTOMOTIVE', 'MUSICAL_INSTRUMENTS', 'OTHER') NOT NULL DEFAULT 'OTHER';
