export enum AUCTION_STATUSES {
  PENDING = 'PENDING',
  READY = 'READY',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  CANCELED = 'CANCELED',
  COMPLETED = 'COMPLETED',
  EXTENDED = 'EXTENDED',
}

export type AuctionStatus =
  (typeof AUCTION_STATUSES)[keyof typeof AUCTION_STATUSES];

export const PUBLIC_AUCTION_STATUSES = {
  READY: AUCTION_STATUSES.READY,
  OPEN: AUCTION_STATUSES.OPEN,
  CLOSED: AUCTION_STATUSES.CLOSED,
  COMPLETED: AUCTION_STATUSES.COMPLETED,
  EXTENDED: AUCTION_STATUSES.EXTENDED,
} as const;

export type PublicAuctionStatus =
  (typeof PUBLIC_AUCTION_STATUSES)[keyof typeof PUBLIC_AUCTION_STATUSES];
