export const NOTIFICATION_TYPE = {
  MESSAGE: 'MESSAGE',
  FOLLOW_REQUEST: 'FOLLOW_REQUEST',
  FOLLOW_ACCEPTED: 'FOLLOW_ACCEPTED',
  AUCTION_CREATED: 'AUCTION_CREATED',
  AUCTION_UPDATED: 'AUCTION_UPDATED',
  AUCTION_CANCELLED: 'AUCTION_CANCELLED',
  AUCTION_STARTED: 'AUCTION_STARTED',
  AUCTION_EXTENDED: 'AUCTION_EXTENDED',
  AUCTION_COMPLETED: 'AUCTION_COMPLETED',
  AUCTION_REOPENED: 'AUCTION_REOPENED',
  AUCTION_CLOSED: 'AUCTION_CLOSED',
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];
