export const  MAX_PRODUCT_DOCUMENTS = 10
export const MAX_PRODUCT_IMAGES = 10

export enum PRODUCT_STATUSES {
  DRAFT = 'DRAFT',
  READY = 'READY',
  AUCTIONING = 'AUCTIONING',
  SOLD = 'SOLD',
  REMOVED = 'REMOVED',
}

export type ProductStatus = (typeof PRODUCT_STATUSES)[keyof typeof PRODUCT_STATUSES];

export enum PUBLIC_CATEGORIES {
  ELECTRONICS = 'ELECTRONICS',
  COMPUTERS = 'COMPUTERS',
  PHONES = 'PHONES',
  CAMERAS = 'CAMERAS',
  FASHION = 'FASHION',
  JEWELRY = 'JEWELRY',
  WATCHES = 'WATCHES',
  HOME = 'HOME',
  FURNITURE = 'FURNITURE',
  BOOKS = 'BOOKS',
  ART = 'ART',
  TOYS = 'TOYS',
  FIGURES = 'FIGURES',
  COLLECTIBLES = 'COLLECTIBLES',
  ANTIQUES = 'ANTIQUES',
  SPORTS = 'SPORTS',
  AUTOMOTIVE = 'AUTOMOTIVE',
  MUSICAL_INSTRUMENTS = 'MUSICAL_INSTRUMENTS',
  OTHER = 'OTHER',
}

export type PublicCategory =
  (typeof PUBLIC_CATEGORIES)[keyof typeof PUBLIC_CATEGORIES];
