-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('MESSAGE', 'FOLLOW_REQUEST', 'FOLLOW_ACCEPTED', 'AUCTION_CREATED', 'AUCTION_UPDATED', 'AUCTION_CANCELLED', 'AUCTION_STARTED', 'AUCTION_EXTENDED', 'AUCTION_COMPLETED', 'AUCTION_REOPENED', 'AUCTION_CLOSED') NOT NULL;
